name: Automated publish Actions
on: push

jobs:
  publish-module:
    name: Publish Module to PowerShell Gallery
    runs-on: ubuntu-latest

    steps:
      - name: perform publish
        uses: pcgeek86/publish-powershell-module-action@v20
        with:
          NuGetApiKey: ${{ secrets.PS_GALLERY_KEY }}
